# Generated by Django 5.0.7 on 2024-08-06 16:31

import django.db.models.deletion
import item.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('quantity', models.IntegerField(default=0, validators=[item.models.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_with_prescription', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                               to='item.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='order_date')),
                ('item',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='item.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user',
                                           to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
