services:
  web:
    build: .
    volumes:
      - .:/code

  web_migrate:
    extends:
      service: web
    command: python manage.py migrate

  web_run_tests:
    extends:
      service: web
    command: python manage.py test item.tests core.tests

  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
